# 1. Basic Julia

## Syntax and unicode

1. Assingment in Julia is done with the `=` sign. 
- You can assign *anything* to a variable binding.
- The variable names can include pretty much any Unicode character.
- Strings are created between double quotes `"` while the single quotes `'` are used for characters only.
- Most Julia editors offer "LaTeX Completion". Pressing e.g. `\delta` and then TAB will create the corresponding Unicode character using the LaTeX syntax.
- **All Julia operations return a value**. This includes assingment.

Here are some examples:

In [1]:
x = 3

3

In [2]:
y = x ^ 2.5 # powers with ^

15.588457268119896

In [3]:
δ = "αbasf" # type \delta and then press TAB

"αbasf"

In [4]:
😺, 😀, 😞 = 1, 0, -1 # do e.g. \:smile: <TAB>

(1, 0, -1)

In [5]:
😺 + 😞 == 😀

true

Since assignement returns the value, by default this value is printed. This is **AMAZING**, but you can also silence printing by adding `;` to the end of the expression:

In [6]:
x = 3;

Most julia operators have their `=` version, which updates something with its own value

In [7]:
x += 3
x -= 3
x *=2
x /= 2

3.0

Literal numbers can multiply anything without having to put `*` inbetween, as long as the number is on the left side:

In [8]:
5x - 12.54y * 1.2e-5x

14.99296274685088

---

Everything that exists in Julia has a certain **Type**. (e.g. numbers can be integers, floats, rationals). This is extremely important, and a core reason of the language's performance (more on Types on the second session).

To find the type of a thing in Julia you simply use `typeof(thing)`:

In [9]:
typeof(😺)

Int64

In [10]:
typeof(1.5)

Float64

In [11]:
typeof("asdf")

String

Lastly, you can interpolate any expression into a string using `$(expression)`

In [12]:
"the value of the cat face (😺) is $(😺)"

"the value of the cat face (😺) is 1"

In [13]:
"I am doing math inside a string: $(y^2 - x)"

"I am doing math inside a string: 240.0"

## Basic collections

Indexing a collection (like an array or a dictionary) in Julia is done with brackets: `collection[index]`. The `index` is typically an integer, although some structures can have arbitrary indices (like a dictionary), and you can define any indexing type for any collection you want (bit advanced tho').

### Tuples
Tuples are ordered immutable collections of elements. They are mostly used when the elements are not of the same type with each other and are intended for small collections.

Syntax:

```julia
(item1, item2, ...)```

In [14]:
myfavoritethings = ("penguins", "cats", π)

("penguins", "cats", π)

In [15]:
myfavoritethings[1]

"penguins"

In [16]:
typeof(myfavoritethings[3])

Irrational{:π}

### NamedTuples

These are exactly like tuples but also assign a name to each variable they contain. They rest between the `Tuple` and `Dict` type in their use.

Their syntax is:
```julia
(key1 = val1, key2 = val2, ...)
```
For example:

In [17]:
nt = (x = 5, y = "str", z = 5//3)

(x = 5, y = "str", z = 5//3)

These objects can be accessed with `[1]` like normal tuples, but also with the syntax `.key`:

In [18]:
nt[1] == nt.x

true

### Dictionaries
Dictionaries are unordered mutable collections of pairs key-value. They are intended for sets of relational data, that is accessed via a key. Dictionaries have a specific type for keys and values.

Syntax:
```julia
Dict(key1 => value1, key2 => value2, ...)```

A good example of a dictionary is a contacts list, where we associate names with phone numbers.

In [19]:
myphonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String,String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [20]:
myphonebook["Jenny"]

"867-5309"

New entries can be added to the above dictionary, because it is mutable. However, the key of the entry must be of type `String` and the value of the entry must be of type `String`.

In [21]:
myphonebook["BuzzLightyear"] = "∞ and beyond"

myphonebook # this displays the phonebook

Dict{String,String} with 3 entries:
  "Jenny"         => "867-5309"
  "BuzzLightyear" => "∞ and beyond"
  "Ghostbusters"  => "555-2368"

### Arrays

The standard Julia `Array` is a mutable and ordered collection of items of the same type.
The dimensionality of the Julia array is important. A `Matrix` is an array of dimension 2. A `Vector` is an array of dimension 1. The *element type* of an array contains is irrelevant to its dimension!

**i.e. a Vector of Vectors of Numbers and a Matrix of Numbers are two totally different things!**

Syntax: <br>
```julia
[item1, item2, ...]```


For example:

In [22]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

5-element Array{String,1}:
 "Ted"     
 "Robyn"   
 "Barney"  
 "Lily"    
 "Marshall"

In [23]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [24]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Array{Any,1}:
 1       
 1       
 2       
 3       
  "Ted"  
  "Robyn"

As mentioned, the type of the elements of an array must be the same. Yet above we mix numbers with strings! I wasn't lying though; the above array is an **unoptimized** version that can hold **any** thing. You can see this in the "type" of the array, whicn is to the left of its dimenmsionality: `Array{TypeOfTheThings, Dimensionality}`. For `mixture` it is `Any`.

Arrays of other data structures, e.g. vectors or dictionaries, or anything, as well as multi-dimensional arrays are possible:

In [25]:
vec_vec_num = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]   
 [4, 5]      
 [6, 7, 8, 9]

In [26]:
R = rand(4, 3)

4×3 Array{Float64,2}:
 0.24562   0.560553   0.0469364
 0.66452   0.0773144  0.737095 
 0.167162  0.863134   0.99905  
 0.285631  0.800522   0.703961 

In [27]:
R[1,2] # two dimensional indexing

0.5605532823837189

Since arrays are mutable we can change their entries, or even add new ones:

In [28]:
fibonacci[1] = 15
fibonacci

7-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13

In [29]:
push!(fibonacci, 16)
fibonacci

8-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13
 16

The functions `push!` and `pop!` are useful with arrays, as they allow you to "add one element the the end" of the array or "remove the last element" of the array.

In [30]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [31]:
push!(x, 5)

4-element Array{Int64,1}:
 1
 2
 3
 5

In [32]:
pop!(x) # this returns the removed element

5

In [33]:
x

3-element Array{Int64,1}:
 1
 2
 3

Lastly, for multidimension arrays, the `:` symbol is useful, which means to "select all elements in this dimension".

In [34]:
x = rand(3,3)

3×3 Array{Float64,2}:
 0.259839  0.518783  0.566524
 0.61348   0.537778  0.996275
 0.954273  0.245197  0.915614

In [35]:
x[:, 1] # it means to select the first column

3-element Array{Float64,1}:
 0.25983916233169335
 0.6134796380905323 
 0.95427330451638   

### Ranges
Ranges are useful shorthand notations that define a "vector" (one dimensional array). This is done with the following syntax:
```
start:step:end
range(start, end; length = ...)
range(start, end; step = ...)
```

In [36]:
r = 0:0.01:5

0.0:0.01:5.0

Ranges are not unique to numeric data, and can be used with anything that extends their interface, e.g.

In [37]:
letterrange = 'a':'z'

'a':1:'z'

As ranges are printed in this short form, to see all their elements you can use `collect`, to transform the range into a `Vector`.

In [38]:
collect(letterrange)

26-element Array{Char,1}:
 'a'
 'b'
 'c'
 'd'
 'e'
 'f'
 'g'
 'h'
 'i'
 'j'
 'k'
 'l'
 'm'
 'n'
 'o'
 'p'
 'q'
 'r'
 's'
 't'
 'u'
 'v'
 'w'
 'x'
 'y'
 'z'

It is important to understand that ranges **do not store all elements in memory** like `Vector`s. Instead they produce the elements on the fly when necessary, and therefore are in general preferred over `Vector`s if the data is equi-spaced. 

Lastly, ranges are typically used to index into arrays. One can type `A[1:3]` to get the first 3 elements of `A`, or `A[end-2, end]` to get the last three elements of `A`. If `A` is multidimension, the same type of indexing can be done for any dimension:

In [39]:
A = rand(10, 10)
A[1:3, 1]

3-element Array{Float64,1}:
 0.6797629477130382
 0.4302665560919703
 0.6485000678433464

In [40]:
A[1:3, 1:3]

3×3 Array{Float64,2}:
 0.679763  0.555084  0.16689 
 0.430267  0.112791  0.324311
 0.6485    0.400739  0.407839

In addition one can use colon `:` to "get all elements in this dimension"

In [41]:
A[3, :]

10-element Array{Float64,1}:
 0.6485000678433464 
 0.4007388066792372 
 0.40783899830432824
 0.6024021188911011 
 0.11649820076937378
 0.22711718920206003
 0.3997924177581538 
 0.7374699956658499 
 0.7339682927964521 
 0.27849039008957566

### List comprehension
The list comprenhension syntax `[expression(a) for a in collection if condition(a)]` is available to make a vector. The `if` part is optional.

In [42]:
[a^2 for a in 1:10 if iseven(a)]

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

## Iteration
Iteration in Julia is high-level. This means that not only it has an intuitive and simple syntax, but also iteration works with anything that can be iterated. Iteration can also be extended (more on that later).


### `for` loops

A `for` loop iterates over a container and executes a piece of code, until the iteration has gone through all the elements of the container. The syntax for a `for` loop is

```julia
for *var* in *loop iterable*
    *loop body*
end
```

*you will notice that all Julia code-blocks end with `end`*

In [43]:
for n in 1:5
    println(n)
end

1
2
3
4
5


The nature of `var` depends on what the iterating container has. For example, when iterating over a dictionary one iterates over pairs of key-value.

In [44]:
for (key, val) in myphonebook
    println("The number of $key is $val")
end

The number of Jenny is 867-5309
The number of BuzzLightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


### `while` loops

A `while` loop executes a code block until a boolean condition check (that happens at the start of the block) becomes `false`. Then the loop terminates (without executing the block again). The syntax for a standard `while` loop is

```julia
while *condition*
    *loop body*
end
```

In [45]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5



## Conditionals

Conditionals execute a specific code block depending on what is the outcome of a given boolean check. Notice that as with other languages `&, |` are the boolean and and or operators.

#### with `if`

In Julia, the syntax

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```

evaluates the conditions sequentially and executes the code-block of the first true condition.

In [46]:
x, y = 5, 6
if x > y
    x
else
    # all Julia code blocks by default 
    # return the last executed expression
    y
end

6

#### with ternary operators

For this last block, we could instead use the ternary operator with the syntax

```julia
a ? b : c
```

which equates to 

```julia
if a
    b
else
    c
end
```

In [47]:
x > y ? x : y

6

Notice that both the boolean conditions, as well as the conditional code blocks, can be nested and chained to arbitrary degree. E.g. this is normal syntax:

```julia
y > w ? 13 : z < x/2 ? 14 : 15
```

which is made more readable with using `()`:
```julia
y > w ? 13 : (z < x/2 ? 14 : 15)
```

#### `break` and `continue`
The keywords `continue` and `break` are often used with conditionals to skip an iteration or completely stop the iteration code block.

In [48]:
N = 1:100
for n in N
    isodd(n) && continue
    println(n)
    n > 10 && break
end

2
4
6
8
10
12


## Functions
Functions are the bread and butter of Julia, which heavily supports functional programming.
Functions are objects by themselves and can be used as any other Julia value.

Functions are declared with two ways:

In [49]:
function f(x)
    x^2      # all Julia code blocks by default 
             # return the last executed expression
end

f(x) = x^2  # equivalent with above

f (generic function with 1 method)

And called using their name and parenthesis `()` enclosing the calling arguments:

In [50]:
f(5)

25

Functions in Julia support optional positional arguments, as well as keyword arguments. The positional arguments are **always** given by their order, while they keyword arguments are **always** given by their keyword. Keywords are defined by using `;`. Example:

In [51]:
function g(x, y = 5; z = 2)
    x*z*y 
end

g (generic function with 2 methods)

In [52]:
g(5) # give x. default y, z

50

In [53]:
g(5, 3) # give x, y. default z

30

In [54]:
g(5; z = 3) # give x, z. default y

75

In [55]:
g(2, 4; z = 1.5) # give everything

12.0

### Duck-typing
Julia supports the "duck typing" approach. Simply put, functions work on whatever imput makes sense given their operations. This can be restricted if need be. 

In our example with `g`, anything that supports the function `*` will work.

In [56]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.666244  0.355421   0.186047
 0.36665   0.938642   0.404782
 0.478083  0.0924313  0.151571

In [57]:
g(A)

3×3 Array{Float64,2}:
 6.66244  3.55421   1.86047
 3.6665   9.38642   4.04782
 4.78083  0.924313  1.51571

In [58]:
g(A, A; z = A)

3×3 Array{Float64,2}:
 0.798783  0.814609  0.406096
 1.1491    1.30945   0.647234
 0.453712  0.418894  0.211252

In [59]:
g("string", "string"; z = "string") # * is string concatenation

"stringstringstring"

In [60]:
g("string", 5)

MethodError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(!Matched::Complex{Bool}, ::Real) at complex.jl:305
  *(!Matched::Missing, ::Number) at missing.jl:115
  ...

Now we got an error because the operation `String*Number` is not supported by default in Julia.

##  Passing by reference: mutating vs. non-mutating functions

Mutable entities in Julia are passed by reference if possible. What does this mean? Well, you can divide Julia variables into two categories: **mutable** and **immutable**. Mutable means that the values of your data can be changed in-place, i.e. literally in the place in memory the variable is stored in the computer. Immutable data cannot be changed after creation, and thus the only way to change part of immutable data is to actually make a brand new immutable object from scratch. Use `isimmutable(v)` to check if value `v` is immutable or not.

For example, `Vector`s are mutable in Julia:

In [61]:
x = [5, 5, 5]
x[1] = 6 # change first entry of x

6

But e.g. `Tuple`s are immutable:

In [62]:
x = (5, 5, 5)
x[1] = 6

MethodError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [63]:
x = (6, 5, 5)

(6, 5, 5)

Julia **passes values by reference**. This means that if a mutable object is given to a function, and this object is mutated inside the function, the final result is kept at the passed object. E.g.:

In [64]:
function add3!(x)
    x[1] += 3
    return x
end

x = [5, 5, 5]
add3!(x)
x

3-element Array{Int64,1}:
 8
 5
 5

**By convention**, functions with name ending in `!` alter their (mutable) arguments and functions lacking `!` do not. Typically the first argument of a function that ends in `!` is mutated.

For example, let's look at the difference between `sort` and `sort!`.

In [65]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [66]:
sort(v)

3-element Array{Int64,1}:
 2
 3
 5

In [67]:
v

3-element Array{Int64,1}:
 3
 5
 2

`sort(v)` returns a sorted array that contains the same elements as `v`, but `v` is left unchanged. <br><br>

On the other hand, when we run `sort!(v)`, the contents of v are sorted within the array `v`.

In [68]:
sort!(v)

3-element Array{Int64,1}:
 2
 3
 5

In [69]:
v

3-element Array{Int64,1}:
 2
 3
 5

### The help system

Typing `?` followed by a function (or type) name will display its documentation string

In [70]:
?typeof

search: typeof typejoin TypeError



```
typeof(x)
```

Get the concrete type of `x`.

# Examples

```jldoctest
julia> a = 1//2;

julia> typeof(a)
Rational{Int64}

julia> M = [1 2; 3.5 4];

julia> typeof(M)
Array{Float64,2}
```


## Broadcasting
Julia compiles efficient machine code that is typically fast. This means that you don't have to vectorize your code; standard `for` loops are fast (sometimes *faster* than vectorized code).

However the need often arises to apply some operations across multiple arguments element-wise. This is called **broadcasting**.

In Julia broadcasting is possible for any function, basic or user-defined. It is done via the simple syntax of adding a dot `.` before the parenthesis in the function call: `g.(x)`. 

Let's recall the previously defined `g`, now without keywords (broadcasting does not work on keywords)

In [71]:
function h(x, y = 5, z = 2)
    x*y*z 
end

h (generic function with 3 methods)

Let's now apply it to a vector `x`

In [72]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [73]:
h.(x)

3-element Array{Int64,1}:
 10
 20
 30

Let's now use vectors for both `y` and `z`:

In [74]:
y, z = rand(3), rand(3)

([0.666092635171196, 0.4365163639602674, 0.1756217864918781], [0.6669969267187503, 0.6889421310854871, 0.5702433516840761])

In [75]:
h.(x, y, z)

3-element Array{Float64,1}:
 0.4442817405691815
 0.6014690280809495
 0.3004414684736213

Same works even with matrices, or any other iterable. Julia will try to automatically deduce what is broadcastable and what should be the size of the output. E.g.:

In [76]:
x = fill(3, (3,3))

3×3 Array{Int64,2}:
 3  3  3
 3  3  3
 3  3  3

In [77]:
y, z = ones(3), fill(2, 3)

([1.0, 1.0, 1.0], [2, 2, 2])

In [78]:
h.(x, y, z)

3×3 Array{Float64,2}:
 6.0  6.0  6.0
 6.0  6.0  6.0
 6.0  6.0  6.0

If one wants to make an exponential range, they just use broadcasting, e.g.

In [79]:
e = 10.0 .^ (-3:3)

7-element Array{Float64,1}:
    0.001
    0.01 
    0.1  
    1.0  
   10.0  
  100.0  
 1000.0  

# 2. Linear algebra in Julia

## Basic linalg operations

First let's define a random matrix

In [80]:
A = rand(1:10, (3,3)) # this will take random numbers from 1:10

3×3 Array{Int64,2}:
 2  9  8
 1  3  7
 3  2  1

and a vector of ones

In [81]:
x = fill(1.0, (3))

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

Notice the dimensionality difference between `A` and `x`! Julia defines the aliases `Vector{Type}=Array{Type,1}` and `Matrix{Type}=Array{Type,2}`. 

Many of the basic operations are the same as in other languages:

In [82]:
b = A*x # matrix-vector multiplication

3-element Array{Float64,1}:
 19.0
 11.0
  6.0

As in other languages `A'` is the conjugate transpose

In [83]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 2  1  3
 9  3  2
 8  7  1

Notice that the transpose operation (like many others) is *lazy* in Julia. This means that there is no numeric computation is happening when we write `A'`. The transposition is taken into account once one uses the matrix in an operation, like below, and still there is no new matrix created!

Julia allows us to write transposed multiplication this without `*`

In [84]:
A'A

3×3 Array{Int64,2}:
 14  27   26
 27  94   95
 26  95  114


The problem $Ax=b$ for ***square*** $A$ is solved by the \ function.

In [85]:
b = A*x
A\b # this should give x

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

## Special matrix structures

Matrix structure is very important in linear algebra. To see *how* important it is, let's work with a larger linear system. Use the `LinearAlgebra` standard package to get access to structured matrices:

In [86]:
using LinearAlgebra

In [87]:
n = 1000
A = randn(n,n); # a nxn matrix with normally distributed numbers

Julia can often infer special matrix structure

In [88]:
Asym = A + A'
issymmetric(Asym)

true

but sometimes floating point error might get in the way.

In [89]:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()

-0.08986975137139719

In [90]:
issymmetric(Asym_noisy)

false

Luckily we can declare structure explicitly with, for example, `Diagonal`, `Triangular`, `Symmetric`, `Hermitian`, `Tridiagonal` and `SymTridiagonal`.

In [91]:
Asym_explicit = Symmetric(Asym_noisy);

Using explicit structures (e.g. `Triangular` can have both performance advantages in specific algorithms, but also allow to use algorithms that only exist given a specific structure!

#### performance benefit
Using the `Tridiagonal` and `SymTridiagonal` types to store tridiagonal matrices makes it possible to work with potentially very large tridiagonal problems. The following problem would not be possible to solve on a laptop if the matrix had to be stored as a (dense) `Matrix` type.

In [92]:
n = 1_000_000;
A = SymTridiagonal(randn(n), randn(n-1));
@time eigmax(A)

  0.595737 seconds (548.19 k allocations: 210.535 MiB, 13.73% gc time)


6.368480866240429

# 3. Performance

Julia matches the performance of C/Fortran not because of better hardware or better compilers than Python has, but because of design. Julia is interactive like Python, but it is not an interpreted language, it is a **compiled** one. This means that **every function call in Julia first gets compiled, based on the exact input types**. Then it is executed.

*(this compilation only happens once for each unique combination of input types)*

Earlier we mentioned that everything in Julia has a `Type` associated with it. When the compiler compiles a function, these types of every variable can be tracked throughout the function and all datastructures are mapped uniquely and deterministically all the way from input to output. This allows the compiler to make all the optimizations that e.g. the compilation of a C language code would do. And this (in a nutshell) is what results in the same performance as C/Fortran.

## Type stability

This tracking of types mentioned above only works if **the type of every variable remains the same type throughout the function's operations**. Notice the distinction: the _type_ (i.e. all floating point variables remain floats) is constant, but of course the _value_ could change (i.e. going from `515134.515` to `123415.242` is fine).

What if this doesn't happen? Then we have the case of **Type instability**, which is what makes beginner's code slow in 99% of the cases. 

Let's look at the following illustrative scenario:

In [93]:
function unstable()
    x = 1
    for i = 1:10
        x /= rand()
    end
    return x
end

function stable()
    x = 1.0
    for i = 1:10
        x /= rand()
    end
    return x
end

stable (generic function with 1 method)

Before we run the code we can put things into context, by asking

In [94]:
(typeof(1.0), typeof(1))

(Float64, Int64)

In [95]:
using BenchmarkTools # Julia package for advanced (and more accurate) benchmarking
@btime unstable();
@btime stable();

  59.169 ns (0 allocations: 0 bytes)
  56.635 ns (0 allocations: 0 bytes)


The reason the `stable` version is faster than the `unstable` is because the type of `x` throughtout the function is not constant. It goes from `Int` at its definition `x = 1` to a `Float64` in the operation `x = x / rand()`, since by definition in Julia `Int / Float64` gives `Float64`.

*Quick notice: this type instability problem becomes much, much worse if the instability happens in more than one variable, if the instability happens with more than 2 types, or if the types involved in the instability are much more complicated*

### Scopes

In general Julia has two scopes: global scope (the one we use here, in this notebook) and local scope. Local scope is introduced by most code blocks, e.g. functions, `for` or `while` loops but *not* from conditional code blocks (`if`). The details of the scopes are mostly relevant for package development and can be found in the [Julia manual](https://docs.julialang.org/en/latest/manual/variables-and-scoping/). 

What is important for us is that by definition, **everything in global scope is type-unstable** and thus not performant. This happens because Julia is not a statically typed language, but a dynamically typed one. Therefore one can do

In [96]:
x = 5
x = "string"

"string"

which is not possible in e.g. C.

The performance that global scope has in code is truly massive:

In [97]:
x, y = rand(1000), rand(1000)
a = 0.0
@btime for i in 1:length(x)
    global a += x[i]^2 + y[i]^2
end

function localf(x, y)
    a = zero(eltype(x))
    for i in 1:length(x)
        a += x[i]^2 + y[i]^2
    end
    return a
end

@btime localf(x, y);

  138.200 μs (7980 allocations: 140.33 KiB)
  754.545 ns (1 allocation: 16 bytes)


### Conclusions so far

1. **Put all performance critical parts of your code inside a function** to avoid global scope
2. **Ensure that your functions are type-stable**

## Allocation

Another thing that is important for performance is allocation. What must be understood is that when one writes

In [98]:
x = rand(1000)

1000-element Array{Float64,1}:
 0.00019229734312875557
 0.6401517906101497    
 0.9434442738641442    
 0.07662062753665766   
 0.08679789728027831   
 0.749153163329489     
 0.3601278519070257    
 0.5018469350390313    
 0.6150821034456682    
 0.11543588106797675   
 0.6486345432346583    
 0.25678000528564193   
 0.6525624827570018    
 ⋮                     
 0.9799958377121687    
 0.1274288790744833    
 0.0814330092465867    
 0.48501138894473317   
 0.9372264435154751    
 0.48450265044857477   
 0.1485677054186363    
 0.43719534059999      
 0.5812924052777648    
 0.984765130555135     
 0.2520009847204272    
 0.012357105125267998  

this *allocates* some part of your memory to store this **mutable** container that `x` represents. Creating mutable things always allocates memory. In general when you are creating something mutable you always pay two costs:

1. the cost to actually calculate the numbers that go into this thing (here e.g. the cost of calling `rand()` a thousand times)
2. the cost to allocate some memory to store 1000 numbers of type `Float64`.

In general you should try to avoid allocations, by more clever design of your algorithms and pre-allocating as much as possible, as is instructed by this section of [Julia's performance tips](https://docs.julialang.org/en/latest/manual/performance-tips/#Pre-allocating-outputs-1).

### Example: using `mul!` for matrix multiplication

If `A, B` are two square matrices (of same size), then `A*B` will make a *new* matrix. However, the function `mul!(C, A, B)` will not make a new one and instead write the result in-place in `C`. Here is an example that demonstrates how important avoiding allocations really is for performance:

In [99]:
using LinearAlgebra

function randmul(n)
    A = fill(rand(), n, n); B = fill(rand(), n, n)
    return sum(A*B)
end

function randmul!(A, B, C)
    fill!(A, rand()); fill!(B, rand())
    mul!(C, A, B)
    return sum(C)
end

randmul! (generic function with 1 method)

In [100]:
n = 100;
A = fill(rand(), n, n)
B = copy(A); C = copy(A);

# compile
randmul(n)
randmul!(A, B, C);

In [101]:
using BenchmarkTools 
@btime randmul($n);
@btime randmul!($A, $B, $C);

  61.500 μs (6 allocations: 234.61 KiB)
  48.299 μs (0 allocations: 0 bytes)


### Conclusions so far

1. **Try to create as little new large entities in your function as possible**, to avoid memory allocations.
2. **Pre-allocate the large and central containers of your function**, and pass them into subsequent operations.

# Exercises
## Collatz conjecture
Given a positive integer, create a function that counts the steps it takes to reach `1` following the [Collatz conjecture algorithm](https://en.wikipedia.org/wiki/Collatz_conjecture). *Hint: use the `isodd` function*.

## Fibonacci numbers
Using recursion (a function that calls itself) create a function that given `n` it returns the `n`-th [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number). Apply it using broadcast to `1:8` to get the result `[1,1,2,3,5,8,13]`.

## Logistic map
Create a function that given `r, x0, N` it creates an orbit of length `N` of the logistic map $x_{n+1} = f(x) = rx(1-x)$. This map produces an orbit iteratively, i.e. starting from `x0` one applies `f(x0)` to get `x1`, and then applies `f(x1)` to get `x2`, and so on. *Hint: use `zeros` or `fill` to initialize a vector, instead of starting with an empty one and using `push!`*.

## Counting nucleotides
Create a function that given a DNA strand (as a `String`, e.g. `"AGAGAGATCCCTTA"`) it counts how much of each nucleotide (A G T or C) is present in the strand. The function should throw an error (using `error`) if an invalid nucleotide is encountered.

There are two ways to solve this one: either making a dictionary and using `haskey` or using `count` in combination with `occursin`. Test your result with `"ATATATAGGCCAX"` and `"ATATATAGGCCAA"`.

## Hamming distance
Create a function that calculates the Hamming distance of two equal DNA strands, given as strings. This distance is defind by counting (sequentially) the number of non-equal letters in the two strands, e.g. `"ATA"` and `"ATC"` have distance of 1, while `"ATC"` and `"CAT"` have distance of 3. 

*Hint: this exercise has a one-liner solution, using the `zip` and `count` functions.*

## Some performance exercise
TODO.