# 1. Basic Julia

In the first section we will overview basic Julia syntax, data structures, etc. If you are feel quite advanced in programming already feel free to wonder around until we get to the second section, which is about writing performant code.

## Syntax and unicode

1. Assignment in Julia is done with the `=` sign. 
- You can assign *anything* to a variable binding.
- The variable names can include pretty much any Unicode character.
- Strings are created between double quotes `"` while the single quotes `'` are used for characters only.
- Most Julia editors offer "LaTeX Completion". Pressing e.g. `\delta` and then TAB will create the corresponding Unicode character using the LaTeX syntax.
- **All Julia operations return a value**. This includes assignment.

Here are some examples:

In [88]:
x = 3

3

In [89]:
y = x ^ 2.5 # powers with ^

15.588457268119896

In [90]:
δ = "αbasf" # type \delta and then press TAB

"αbasf"

In [91]:
😺, 😀, 😞 = 1, 0, -1 # do e.g. \:smile: <TAB>

(1, 0, -1)

In [92]:
😺 + 😞 == 😀

true

Since assignment returns the value, by default this value is printed. This is **AMAZING**, but you can also silence printing by adding `;` to the end of the expression:

In [93]:
x = 3;

Most julia operators have their `=` version, which updates something with its own value

In [94]:
x += 3 # x = x + 3
x -= 3
x *=2
x /= 2

3.0

Literal numbers can multiply anything without having to put `*` inbetween, as long as the number is on the left side:

In [95]:
5x - 12.54y * 1.2e-5x

14.99296274685088

---

Everything that exists in Julia has a certain **Type**. (e.g. numbers can be integers, floats, rationals). This is extremely important, and a core reason of the language's performance (more on Types on the second session).

To find the type of a thing in Julia you simply use `typeof(thing)`:

In [96]:
typeof(😺)

Int64

In [97]:
typeof(1.5)

Float64

In [98]:
typeof("asdf")

String

Lastly, you can interpolate any expression into a string using `$(expression)`

In [99]:
"the value of the cat face (😺) is $(😺)"

"the value of the cat face (😺) is 1"

In [100]:
"I am doing math inside a string: $(y^2 - x)"

"I am doing math inside a string: 240.0"

## Basic collections

Indexing a collection (like an array or a dictionary) in Julia is done with brackets: `collection[index]`. The `index` is typically an integer, although some structures can have arbitrary indices (like a dictionary), and you can define any indexing type for any collection you want (bit advanced tho').

**Julia indexing starts from 1**

### Tuples
Tuples are ordered immutable collections of elements. They are mostly used when the elements are not of the same type with each other and are intended for small collections.

Syntax:

```julia
(item1, item2, ...)```

In [101]:
myfavoritethings = ("purple", "cats", π)

("purple", "cats", π)

In [102]:
myfavoritethings[1]

"purple"

### NamedTuples

These are exactly like tuples but also assign a name to each variable they contain. They rest between the `Tuple` and `Dict` type in their use.

Their syntax is:
```julia
(key1 = val1, key2 = val2, ...)
```
For example:

In [103]:
nt = (x = 5, y = "str", z = 5/3)

(x = 5, y = "str", z = 1.6666666666666667)

These objects can be accessed with `[1]` like normal tuples, but also with the syntax `.key`:

In [104]:
nt[1]

5

In [105]:
nt.x # nt[:x]

5

### Dictionaries
Dictionaries are unordered mutable collections of pairs key-value. They are intended for sets of relational data, and typically you want the data to be of the same type. Dictionaries have a specific type for keys and values.

Syntax:
```julia
Dict(key1 => value1, key2 => value2, ...)```

A good example of a dictionary is a contacts list, where we associate names with phone numbers.

In [106]:
myphonebook = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

Dict{String,String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [107]:
myphonebook["Jenny"]

"867-5309"

New entries can be added to the above dictionary, because it is mutable *(I will talk in more detail about mutability in a moment, but for now mutable means that "you can change its values")*. The key of the entry must be of type `String` and the value of the entry must be of type `String`, because these are the types in the original dictionary.

In [108]:
myphonebook["BuzzLightyear"] = "∞ and beyond"

myphonebook # this displays the phonebook

Dict{String,String} with 3 entries:
  "Jenny"         => "867-5309"
  "BuzzLightyear" => "∞ and beyond"
  "Ghostbusters"  => "555-2368"

### Arrays

The standard Julia `Array` is a mutable and ordered collection of items of the same type.
The dimensionality of the Julia array is important. A `Matrix` is an array of dimension 2. A `Vector` is an array of dimension 1. The *element type* of what an array contains is irrelevant to its dimension!

**i.e. a Vector of Vectors of Numbers and a Matrix of Numbers are two totally different things!**

Syntax: <br>
```julia
[item1, item2, ...]```


For example:

In [109]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

5-element Array{String,1}:
 "Ted"     
 "Robyn"   
 "Barney"  
 "Lily"    
 "Marshall"

In [110]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [111]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

6-element Array{Any,1}:
 1       
 1       
 2       
 3       
  "Ted"  
  "Robyn"

As mentioned, the type of the elements of an array must be the same. Yet above we mix numbers with strings! I wasn't lying though; the above array is an **unoptimized** version that can hold **any** thing. You can see this in the "type" of the array, which is to the left of its dimensionality: `Array{TypeOfTheThings, Dimensionality}`. For `mixture` it is `Any`.

Arrays of other data structures, e.g. vectors or dictionaries, or anything, as well as multi-dimensional arrays are possible:

In [112]:
vec_vec_num = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]   
 [4, 5]      
 [6, 7, 8, 9]

If you want to make a matrix, two ways are the most common: (1) specify each entry one by one

In [113]:
matrix = [1 2 3; # elements in same row separated by space
          4 5 6; # semicolon means "go to next row"
          7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

(2) you use a function that initializes a matrix. E.g. `rand(n, m)` will create an `n×m` matrix with uniformly random numbers

In [114]:
R = rand(4, 3)

4×3 Array{Float64,2}:
 0.519171  0.160793  0.781728
 0.655947  0.551174  0.816126
 0.226035  0.918012  0.490806
 0.388249  0.530115  0.455969

In [115]:
R[1,2] # two dimensional indexing

0.16079339440758234

Since arrays are mutable we can change their entries, or even add new ones:

In [116]:
fibonacci = [1, 1, 2, 3, 5, 8, 13]
fibonacci[1] = 15
fibonacci

7-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13

In [117]:
push!(fibonacci, 16)
fibonacci

8-element Array{Int64,1}:
 15
  1
  2
  3
  5
  8
 13
 16

The functions `push!` and `pop!` are useful with arrays, as they allow you to "add one element the the end" of the array or "remove the last element" of the array.

Lastly, for multi-dimensional arrays, the `:` symbol is useful, which means to "select all elements in this dimension".

In [120]:
x = rand(3,3)

3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [119]:
x[:, 1] # it means to select the first column

3-element Array{Float64,1}:
 0.4483534700732059  
 0.7329113520087176  
 0.019330915228872536

### Ranges
Ranges are useful shorthand notations that define a "vector" (one dimensional array). This is done with the following syntax:
```
start:step:end
range(start, end; length = ...)
range(start, end; step = ...)
```

In [121]:
r = 0:0.01:5

0.0:0.01:5.0

Ranges are not unique to numeric data, and can be used with anything that extends their interface, e.g.

In [122]:
letterrange = 'a':'z'

'a':1:'z'

As ranges are printed in this short form, to see all their elements you can use `collect`, to transform the range into a `Vector`.

In [123]:
collect(letterrange)

26-element Array{Char,1}:
 'a'
 'b'
 'c'
 'd'
 'e'
 'f'
 'g'
 'h'
 'i'
 'j'
 'k'
 'l'
 'm'
 'n'
 'o'
 'p'
 'q'
 'r'
 's'
 't'
 'u'
 'v'
 'w'
 'x'
 'y'
 'z'

It is important to understand that ranges **do not store all elements in memory** like `Vector`s. Instead they produce the elements on the fly when necessary, and therefore are in general preferred over `Vector`s if the data is equi-spaced. 

Lastly, ranges are typically used to index into arrays. One can type `A[1:3]` to get the first 3 elements of `A`, or `A[end-2:end]` to get the last three elements of `A`. If `A` is multidimensional, the same type of indexing can be done for any dimension:

In [124]:
A = rand(4, 4)

4×4 Array{Float64,2}:
 0.850934   0.605064  0.350557  0.0609694
 0.0635157  0.642909  0.289173  0.886842 
 0.45913    0.929887  0.83624   0.93098  
 0.418914   0.239356  0.610005  0.906587 

In [125]:
A[1:3, 1]

3-element Array{Float64,1}:
 0.8509344965660368 
 0.0635157135496649 
 0.45912950360046945

In [126]:
A[1:3, 1:3]

3×3 Array{Float64,2}:
 0.850934   0.605064  0.350557
 0.0635157  0.642909  0.289173
 0.45913    0.929887  0.83624 

### List comprehension
The list comprehension syntax `[expression(a) for a in collection if condition(a)]` is available to make a vector. The `if` part is optional.

In [127]:
[a^2 for a in 1:10 if iseven(a)]

5-element Array{Int64,1}:
   4
  16
  36
  64
 100

## Iteration
Iteration in Julia is high-level. This means that not only it has an intuitive and simple syntax, but also iteration works with anything that can be iterated. Iteration can also be extended (more on that later).


### `for` loops

A `for` loop iterates over a container and executes a piece of code, until the iteration has gone through all the elements of the container. The syntax for a `for` loop is

```julia
for *var* in *loop iterable*
    *loop body*
end
```

*you will notice that all Julia code-blocks end with `end`*

In [129]:
for n ∈ 1:5
    println(n)
end

1
2
3
4
5


The nature of `var` depends on what the iterating container has. For example, when iterating over a dictionary one iterates over pairs of key-value.

In [130]:
for (key, val) in myphonebook # pair in myphonebook
    println("The number of $key is $val")
end

The number of Jenny is 867-5309
The number of BuzzLightyear is ∞ and beyond
The number of Ghostbusters is 555-2368


Notice that `for pair in myphonebook` is also valid syntax. Then `pair[1]` would be the `key` and `pair[2]` would be the `val`. But Julia allows you to easily extract them on the header of the `for` loop, which also makes to code clearer.

### `while` loops

A `while` loop executes a code block until a boolean condition check (that happens at the start of the block) becomes `false`. Then the loop terminates (without executing the block again). The syntax for a standard `while` loop is

```julia
while *condition*
    *loop body*
end
```

In [132]:
n = 0
while n < 5
    n += 1
    println(n)
end

1
2
3
4
5



## Conditionals

Conditionals execute a specific code block depending on what is the outcome of a given boolean check. Notice that as with other languages `&, |` are the boolean and and or operators.

#### with `if`

In Julia, the syntax

```julia
if *condition 1*
    *option 1*
elseif *condition 2*
    *option 2*
else
    *option 3*
end
```

evaluates the conditions sequentially and executes the code-block of the first true condition.

In [133]:
x, y = 5, 6
if x > y
    x
else
    # all Julia code blocks by default 
    # return the last executed expression
    y
end

6

#### with ternary operators

For this last block, we could instead use the ternary operator with the syntax

```julia
a ? b : c
```

which equates to 

```julia
if a
    b
else
    c
end
```

In [134]:
x > y ? x : y

6

Notice that both the boolean conditions, as well as the conditional code blocks, can be nested and chained to arbitrary degree. E.g. this is normal syntax:

```julia
y > w ? 13 : z < x/2 ? 14 : 15
```

which is made more readable with using `()`:
```julia
y > w ? 13 : (z < x/2 ? 14 : 15)
```

#### `break` and `continue`
The keywords `continue` and `break` are often used with conditionals to skip an iteration or completely stop the iteration code block.

In [136]:
N = 1:100
for n in N
    isodd(n) && continue
    println(n)
    n > 10 && break
end

2
4
6
8
10
12


## Functions
Functions are the bread and butter of Julia, which heavily supports functional programming.
Functions are objects by themselves and can be used as any other Julia value.

Functions are declared with two ways:

In [137]:
function f(x)
    x^2      # all Julia code blocks by default 
             # return the last executed expression
end

f(x) = x^2  # equivalent with above

f (generic function with 1 method)

And called using their name and parenthesis `()` enclosing the calling arguments:

In [138]:
f(5)

25

Functions in Julia support optional positional arguments, as well as keyword arguments. The **positional** arguments are **always given by their order**, while **keyword** arguments are **always given by their keyword**. Keyword arguments are all the arguments defined in a function after the symbol `;`. Example:

In [139]:
function g(x, y = 5; z = 2)
    x*z*y
end

g (generic function with 2 methods)

In [140]:
g(5) # give x. default y, z

50

In [141]:
g(5, 3) # give x, y. default z

30

In [142]:
g(5; z = 3) # give x, z. default y

75

In [143]:
g(2, 4; z = 1.5) # give everything

12.0

In [144]:
g(2, 4, 2) # keyword arguments can't be specified by position

MethodError: MethodError: no method matching g(::Int64, ::Int64, ::Int64)
Closest candidates are:
  g(::Any, ::Any; z) at In[139]:2
  g(::Any) at In[139]:2

### Duck-typing
Julia supports the "duck typing" approach. Simply put, functions work on whatever input makes sense given their operations. This can be restricted if need be. 

In our example with `g`, anything that supports the function `*` will work.

In [145]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.961034  0.491261  0.474666
 0.538627  0.951596  0.312862
 0.283563  0.117156  0.665408

In [146]:
g(A)

3×3 Array{Float64,2}:
 9.61034  4.91261  4.74666
 5.38627  9.51596  3.12862
 2.83563  1.17156  6.65408

In [147]:
g(A, A; z = A)

3×3 Array{Float64,2}:
 2.06979   1.70533   1.55523 
 1.94127   1.78728   1.41542 
 0.855056  0.642338  0.760294

In [148]:
g("string", "string"; z = "string") # * is string concatenation

"stringstringstring"

In [149]:
g("string", 5)

MethodError: MethodError: no method matching *(::String, ::Int64)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:529
  *(!Matched::Complex{Bool}, ::Real) at complex.jl:305
  *(!Matched::Missing, ::Number) at missing.jl:115
  ...

Now we got an error because the operation `String*Number` is not supported by default in Julia.

##  Passing by reference: mutating vs. non-mutating functions

Mutable entities in Julia are passed by reference if possible. What does this mean? Well, you can divide Julia variables into two categories: **mutable** and **immutable**. Mutable means that the values of your data can be changed in-place, i.e. literally in the place in memory the variable is stored in the computer. Immutable data cannot be changed after creation, and thus the only way to change part of immutable data is to actually make a brand new immutable object from scratch. Use `isimmutable(v)` to check if value `v` is immutable or not.

For example, `Vector`s are mutable in Julia:

In [150]:
x = [5, 5, 5]
x[1] = 6 # change first entry of x
x

3-element Array{Int64,1}:
 6
 5
 5

But e.g. `Tuple`s are immutable:

In [151]:
x = (5, 5, 5)
x[1] = 6

MethodError: MethodError: no method matching setindex!(::Tuple{Int64,Int64,Int64}, ::Int64, ::Int64)

In [152]:
x = (6, 5, 5)

(6, 5, 5)

Julia **passes values by reference**. This means that if a mutable object is given to a function, and this object is mutated inside the function, the final result is kept at the passed object. E.g.:

In [153]:
function add3!(x)
    x[1] += 3
    return x
end

x = [5, 5, 5]
add3!(x)
x

3-element Array{Int64,1}:
 8
 5
 5

**By convention**, functions with name ending in `!` alter their (mutable) arguments and functions lacking `!` do not. Typically the first argument of a function that ends in `!` is mutated.

For example, let's look at the difference between `sort` and `sort!`.

In [154]:
v = [3, 5, 2]

3-element Array{Int64,1}:
 3
 5
 2

In [155]:
sort(v)

3-element Array{Int64,1}:
 2
 3
 5

In [156]:
v

3-element Array{Int64,1}:
 3
 5
 2

`sort(v)` returns a sorted array that contains the same elements as `v`, but `v` is left unchanged. <br><br>

On the other hand, when we run `sort!(v)`, the contents of v are sorted within the array `v`.

In [157]:
sort!(v)

3-element Array{Int64,1}:
 2
 3
 5

In [158]:
v

3-element Array{Int64,1}:
 2
 3
 5

### The help system

Typing `?` followed by a function (or type) name will display its documentation string

In [159]:
?typeof

search: typeof typejoin TypeError



```
typeof(x)
```

Get the concrete type of `x`.

# Examples

```jldoctest
julia> a = 1//2;

julia> typeof(a)
Rational{Int64}

julia> M = [1 2; 3.5 4];

julia> typeof(M)
Array{Float64,2}
```


## Broadcasting
Julia compiles efficient machine code that is typically fast. This means that you don't have to vectorize your code; standard `for` loops are fast (sometimes *faster* than vectorized code).

However the need often arises to apply some operations across multiple arguments element-wise. This is called **broadcasting**.

In Julia broadcasting is possible for any function, basic or user-defined. It is done via the simple syntax of adding a dot `.` before the parenthesis in the function call: `g.(x)`. 

Let's recall the previously defined `g`, now without keywords (broadcasting does not work on keywords)

In [160]:
function h(x, y = 5, z = 2)
    x*y*z 
end

h (generic function with 3 methods)

Let's now apply it to a vector `x`

In [161]:
x = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [162]:
h.(x)

3-element Array{Int64,1}:
 10
 20
 30

Let's now use vectors for both `y` and `z`:

In [163]:
y, z = rand(3), rand(3)

([0.7321279607297009, 0.16019869547209464, 0.17526765364307928], [0.805078409756115, 0.7168818688595757, 0.8310643379601241])

In [164]:
h.(x, y, z)

3-element Array{Float64,1}:
 0.589420414362255  
 0.22968708039780253
 0.4369760896221301 

Same works even with matrices, or any other iterable. Julia will try to automatically deduce what is broadcastable and what should be the size of the output. E.g.:

In [165]:
x = fill(3, (3,3))

3×3 Array{Int64,2}:
 3  3  3
 3  3  3
 3  3  3

In [166]:
y, z = 1:3, 0:2

(1:3, 0:2)

In [167]:
h.(x, y, z)

3×3 Array{Int64,2}:
  0   0   0
  6   6   6
 18  18  18

If one wants to make an exponential range, they just use broadcasting, e.g.

In [168]:
e = 10.0 .^ (-3:3)

7-element Array{Float64,1}:
    0.001
    0.01 
    0.1  
    1.0  
   10.0  
  100.0  
 1000.0  

*(notice that for infix operators (like `+, -`) the `.` is put before the operator)*

# 2. Performance

Julia matches the performance of C/Fortran not because of better hardware or better compilers than Python has, but because of design. Julia is interactive like Python, but it is not an interpreted language, it is a **compiled** one. This means that **every function call in Julia first gets compiled, based on the exact input types**. Then it is executed.

*(this compilation only happens once for each unique combination of input types)*

Earlier we mentioned that everything in Julia has a `Type` associated with it. When the compiler compiles a function, these types of every variable can be tracked throughout the function and all datastructures are mapped uniquely and deterministically all the way from input to output. This allows the compiler to make all the optimizations that e.g. the compilation of a C language code would do. And this (in a nutshell) is what results in the same performance as C/Fortran.

## Type stability

This tracking of types mentioned above only works if **the type of every variable remains the same type throughout the function's operations**. Notice the distinction: the _type_ (i.e. all floating point variables remain floats) is constant, but of course the _value_ could change (i.e. going from `515134.515` to `123415.242` is fine).

What if this doesn't happen? Then we have the case of **Type instability**, which is what makes beginner's code slow in 99% of the cases. 

Let's look at the following illustrative scenario:

In [ ]:
function unstable()
    x = 1
    for i = 1:10
        x /= rand()
    end
    return x
end

function stable()
    x = 1.0
    for i = 1:10
        x /= rand()
    end
    return x
end

Before we run the code we can put things into context, by asking

In [169]:
(typeof(1.0), typeof(1), typeof(1/rand()))

(Float64, Int64, Float64)

In [171]:
using BenchmarkTools # Julia package for advanced (and more accurate) benchmarking
@btime unstable();
@btime stable();

  132.244 ns (0 allocations: 0 bytes)
  131.001 ns (0 allocations: 0 bytes)


The reason the `stable` version is faster than the `unstable` is because the type of `x` throughout the function is not constant. It goes from `Int` at its definition `x = 1` to a `Float64` in the operation `x = x / rand()`, since by definition in Julia `Int / Float64` gives `Float64`.

*Quick notice: this type instability problem becomes much, much worse if the instability happens in more than one variable, if the instability happens with more than 2 types, or if the types involved in the instability are much more complicated.*

### Scopes

In general Julia has two scopes: global scope (the one we use here, in this notebook) and local scope. Local scope is introduced by most code blocks, e.g. functions, `for` or `while` loops but *not* from conditional code blocks (`if`). The details of the scopes are mostly relevant for package development and can be found in the [Julia manual](https://docs.julialang.org/en/latest/manual/variables-and-scoping/). 

What is important for us is that by definition, **everything in global scope is type-unstable** and thus not performant. This happens because Julia is not a statically typed language, but a dynamically typed one. Therefore one can do

In [172]:
x = 5
x = "string"

"string"

which is not possible in e.g. C.

The performance that global scope has in code is truly massive:

In [173]:
x, y = rand(1000), rand(1000)
a = 0.0
@btime for i in 1:length(x)
    global a += x[i]^2 + y[i]^2
end

function localf(x, y)
    a = zero(eltype(x))
    for i in 1:length(x)
        a += x[i]^2 + y[i]^2
    end
    return a
end

@btime localf(x, y);

  348.900 μs (7980 allocations: 140.33 KiB)
  2.389 μs (1 allocation: 16 bytes)


### Conclusions so far

1. **Put all performance critical parts of your code inside a function** to avoid global scope
2. **Ensure that your functions are type-stable**

## Allocation

Another thing that is important for performance is allocation. What must be understood is that when one writes

In [175]:
x = rand(2, 2)

2×2 Array{Float64,2}:
 0.278753  0.0102621
 0.434472  0.360526 

this *allocates* some part of your memory to store this **mutable** container that `x` represents. Creating mutable things always allocates memory. In general when you are creating something mutable you always pay two costs:

1. the cost to actually calculate the numbers that go into this thing (here e.g. the cost of calling `rand()`)
2. the cost to allocate some memory to store 1000 numbers of type `Float64`.

In general you should try to avoid allocations, by more clever design of your algorithms and pre-allocating as much as possible, as is instructed by this section of [Julia's performance tips](https://docs.julialang.org/en/latest/manual/performance-tips/#Pre-allocating-outputs-1).

### Example: using `mul!` for matrix multiplication

If `A, B` are two square matrices (of same size), then `A*B` will make a *new* matrix. However, the function `mul!(C, A, B)` will not make a new one and instead write the result in-place in `C`. Here is an example that demonstrates how important avoiding allocations really is for performance:

In [176]:
using LinearAlgebra

function randmul(n)
    A = fill(rand(), n, n); B = fill(rand(), n, n)
    return sum(A*B)
end

function randmul!(C, A, B)
    fill!(A, rand()); fill!(B, rand())
    mul!(C, A, B)
    return sum(C)
end

randmul! (generic function with 1 method)

In [177]:
n = 100;
A = fill(rand(), n, n)
B = copy(A); C = copy(A);

(randmul(n), randmul!(C, A, B))

(153557.6216648124, 97082.35053029115)

In [178]:
using BenchmarkTools 
@btime randmul($n);
@btime randmul!($C, $A, $B);

  111.600 μs (6 allocations: 234.61 KiB)
  107.000 μs (0 allocations: 0 bytes)


Again, in the real world this situation becomes much worse, because the data structures are initialized more often and/or are larger and/or more complicated.

### Conclusions so far

1. **Try to create as little new large mutable entities in your function as possible**, to avoid memory allocations.
2. **Pre-allocate the large and central containers of your function**, and pass them into subsequent operations.

# Exercises
## Collatz conjecture
Given a positive integer, create a function that counts the steps it takes to reach `1` following the [Collatz conjecture algorithm](https://en.wikipedia.org/wiki/Collatz_conjecture) (if $n$ is odd do $n=3n+1$ otherwise do $n=n/2$). Test it with the number 100 to get 25.

*Hint: make a type-stable function by using `÷`, (`\div<TAB>`): In Julia `/` is the floating point division operator and thus `n/m` is always a float number even if `n, m` are integers.*

## Fibonacci numbers
Using recursion (a function that calls itself) create a function that given `n` it returns the `n`-th [Fibonacci number](https://en.wikipedia.org/wiki/Fibonacci_number). Apply it using broadcast to `1:8` to get the result `[1,1,2,3,5,8,13]`.

## Logistic map
Create a function that given `r, x0, N` it creates an orbit of length `N` of the logistic map $x_{n+1} = f(x) = rx(1-x)$. This map produces an orbit iteratively, i.e. starting from `x0` one applies `f(x0)` to get `x1`, and then applies `f(x1)` to get `x2`, and so on. 

*Hint: use `zeros` or `fill` to initialize a vector, instead of starting with an empty one and using `push!`*.

## Counting nucleotides
Create a function that given a DNA strand (as a `String`, e.g. `"AGAGAGATCCCTTA"`) it counts how much of each nucleotide (A G T or C) is present in the strand. The function should throw an error (using `error`) if an invalid nucleotide is encountered. Test your result with `"ATATATAGGCCAX"` and `"ATATATAGGCCAA"`.

*Hint: there are two ways to solve this one: either making a dictionary and using `haskey` or using `count` in combination with `occursin`.*

## Hamming distance
Create a function that calculates the Hamming distance of two equal DNA strands, given as strings. This distance is defined by counting (sequentially) the number of non-equal letters in the two strands, e.g. `"ATA"` and `"ATC"` have distance of 1, while `"ATC"` and `"CAT"` have distance of 3. 

*Hint: this exercise has a one-liner solution, using the `zip` and `count` functions.*

## Babylonian square root
Babylonians knew how to calculate square roots several millennia ago. To get the square root of $y$ they used the algorithm $x_{n+1} = \frac{1}{2}(x_n + \frac{y}{x_n})$ iteratively starting from some value $x_0$ to converge to $x_n \to \sqrt{y}$ as $n\to \infty$. Implement this algortihm in a function `babylonian(y, ε)` that takes some convergence tolerance `ε`. The function should print the amount of steps it took, as well as the square root value.